# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
default_events:
- issues
- repository_dispatch

# The set of permissions needed by the GitHub App. The format of the object uses
# the permission name for the key (for example, issues) and the access type for
# the value (for example, write).
# Valid values are `read`, `write`, and `none`
default_permissions:
  # Repository contents, commits, branches, downloads, releases, and merges.
  # https://developer.github.com/v3/apps/permissions/#permission-on-contents
  contents: write

  # Deployments and deployment statuses.
  # https://developer.github.com/v3/apps/permissions/#permission-on-deployments
  # deployments: read

  # Issues and related comments, assignees, labels, and milestones.
  # https://developer.github.com/v3/apps/permissions/#permission-on-issues
  issues: write

  # Search repositories, list collaborators, and access repository metadata.
  # https://developer.github.com/v3/apps/permissions/#metadata-permissions
  metadata: read

  # Pull requests and related comments, assignees, labels, milestones, and merges.
  # https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests
  pull_requests: write

  # Manage the post-receive hooks for a repository.
  # https://developer.github.com/v3/apps/permissions/#permission-on-repository-hooks
  # repository_hooks: read

  # Manage the post-receive hooks for an organization.
  # https://developer.github.com/v3/apps/permissions/#permission-on-organization-hooks
  # organization_hooks: read


# The name of the GitHub App. Defaults to the name specified in package.json
name: zorber

# The homepage of your GitHub App.
url: https://github.com/giantswarm/zorber

# A description of the GitHub App.
description: Zorber rolls the orbs

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
# Default: true
# public: false
